version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
    ignore:
      # These are peer deps of Cargo and should not be automatically bumped
      - dependency-name: "semver"
      - dependency-name: "crates-io"
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "deps:"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"